// Combate por estados: patrulha, perseguição, preparação, recuperação, esquiva e habilidades.
(()=>{
const configs=new WeakMap();const clamp=(v,a,b,d)=>Number.isFinite(Number(v))?Math.max(a,Math.min(b,Number(v))):d;
function defaults(type={}){const boss=!!type.isBoss,order=window.BossCampaign?.find(q=>q.bossId===type.id)?.order||1;return {detection:boss?720:460,leash:boss?1600:900,attackRange:boss?110:65,attackHeight:boss?140:95,windup:boss?850:650,attackCooldown:boss?1700:2200,chaseSpeed:boss?1.5+order*.06:Math.max(1,Number(type.speed||.6)*1.8),dodgeChance:boss?Math.min(.35,.06+order*.025):0,dodgeCooldown:boss?4200:6000,dodgeDistance:boss?150:95,ability:boss?(order<=3?'agility':order<=6?'rapid':order<=9?'teleport':'mixed'):'none',abilityCooldown:boss?12000:16000,abilityThreshold:boss?75:100,abilityDuration:4000,abilityPower:1.35,burstCount:3,color:boss?'#ff6489':'#bda0ff'};}
function config(e){if(configs.has(e))return configs.get(e);const d=defaults(e.type),a=e.type.ai||{},c={...d,...a};const limits={detection:[100,1800],leash:[200,4000],attackRange:[35,300],attackHeight:[40,220],windup:[250,3000],attackCooldown:[400,10000],chaseSpeed:[.2,8],dodgeChance:[0,.6],dodgeCooldown:[1500,15000],dodgeDistance:[60,250],abilityCooldown:[4000,60000],abilityThreshold:[10,100],abilityDuration:[1000,8000],abilityPower:[1,2.5],burstCount:[2,5]};for(const k in limits)c[k]=clamp(c[k],...limits[k],d[k]);c.leash=Math.max(c.leash,c.detection);if(!['none','agility','teleport','rapid','mixed'].includes(c.ability))c.ability='none';configs.set(e,c);return c;}
const playerBounds=()=>({x:player.position.x,y:player.position.y,width:player.width/player.totalSpriteFrames,height:player.height});
function targetBounds(e){const p=playerBounds(),g=window.ShadowRaids?.petBounds();if(g&&Math.abs(g.x+g.width/2-center(e))<Math.abs(p.x+p.width/2-center(e)))return g;return p;}
const overlap=(a,b)=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;
function center(e){return e.position.x+e.width/2;}
function attackBox(e){const c=config(e),x=center(e);return {x:e.facing==='left'?x-c.attackRange:x,y:canvas.height-floorHeight-c.attackHeight,width:c.attackRange,height:c.attackHeight};}
function canHit(e){return !e.isDead&&player.health>0&&overlap(attackBox(e),targetBounds(e));}
function bounded(e,x){return Math.max(0,Math.min(worldWidth-e.width,x));}
function beginAttack(e,now){const c=config(e);e.windupUntil=now+(e.rapidRemaining?Math.max(250,c.windup*.5):c.windup);e.aiState='preparing';e.warningBox=attackBox(e);}
function impact(e,now){const c=config(e),box=attackBox(e),buff=now<(e.buffUntil||0)||e.rapidRemaining;e.windupUntil=0;e.aiState='recovering';activeEffects.push(new ArcEffect({x:box.x+box.width/2,y:canvas.height-floorHeight,color:c.color,radius:box.width/2,duration:24}));if(canHit(e)){const p=targetBounds(e),damage=e.contactDamage*(buff?c.abilityPower:1);if(p.isGuardian)window.ShadowRaids.hurtPet(damage);else player.takeDamage(damage);updateHud();}if(e.rapidRemaining){e.rapidRemaining--;e.attackReadyAt=now+250;}else e.attackReadyAt=now+c.attackCooldown;}
function startSkill(e,now){const c=config(e);e.skillKind=c.ability==='mixed'?['agility','rapid','teleport'][e.skillCycle++%3]:c.ability;e.skillWindupUntil=now+900;e.aiState='special-preparing';e.abilityReadyAt=now+c.abilityCooldown;if(e.skillKind==='teleport'){const p=targetBounds(e),dir=player.facing==='right'?1:-1;e.teleportX=bounded(e,p.x+p.width/2+dir*(e.width/2+c.attackRange*.65)-e.width/2);}}
function finishSkill(e,now){const c=config(e),kind=e.skillKind;e.skillWindupUntil=0;e.buffUntil=now+c.abilityDuration;activeEffects.push(new ArcEffect({x:center(e),y:canvas.height-floorHeight,color:c.color,radius:130,duration:35}));if(kind==='agility'){e.agilityUntil=now+c.abilityDuration;e.aiState='agility';e.attackReadyAt=now+300;}else if(kind==='teleport'){e.position.x=e.teleportX;const p=targetBounds(e);e.facing=p.x+p.width/2<center(e)?'left':'right';e.direction=e.facing==='left'?-1:1;e.teleportFlashUntil=now+400;e.attackReadyAt=now+300;e.aiState='teleported';}else{e.rapidRemaining=Math.floor(c.burstCount);e.attackReadyAt=now+250;e.aiState='rapid';}}
function tick(e){if(typeof gameState==='undefined'||gameState!=='playing'||player.health<=0||e.isDead)return;const now=performance.now(),c=config(e),p=targetBounds(e),distance=Math.abs(p.x+p.width/2-center(e));
 if(e.skillCycle===undefined)e.skillCycle=0;
 if(e.windupUntil){if(now>=e.windupUntil)impact(e,now);return;}
 if(e.skillWindupUntil){if(now>=e.skillWindupUntil)finishSkill(e,now);return;}
 if(now<(e.dodgeUntil||0))return;
 if(Math.abs(e.position.x-e.baseX)>c.leash){e.aggro=false;e.returning=true;e.rapidRemaining=0;}
 if(!e.returning&&distance<=c.detection&&Math.abs(p.y-e.position.y)<300){e.aggro=true;e.lastSeenAt=now;if(!e.abilityReadyAt)e.abilityReadyAt=now+c.abilityCooldown*.4;}
 if(e.aggro&&distance>c.detection*1.35&&now-(e.lastSeenAt||0)>2600){e.aggro=false;e.returning=true;e.rapidRemaining=0;}
 if(!e.aggro)return;
 e.direction=p.x+p.width/2<center(e)?-1:1;e.facing=e.direction<0?'left':'right';
 if(c.ability!=='none'&&now>=(e.abilityReadyAt||0)&&e.health/e.maxHealth*100<=c.abilityThreshold){startSkill(e,now);return;}
 if(now>=(e.attackReadyAt||0)&&canHit(e))beginAttack(e,now);
 else e.aiState=now<(e.attackReadyAt||0)?'recovering':'chasing';
}
function move(e){const now=performance.now(),c=config(e);if(e.skillWindupUntil||e.windupUntil||now<(e.dodgeUntil||0))return;let direction=e.direction,speed=e.speed;
 if(e.returning){direction=Math.sign(e.baseX-e.position.x);speed=c.chaseSpeed;if(Math.abs(e.position.x-e.baseX)<8){e.returning=false;e.position.x=e.baseX;}e.aiState='returning';}
 else if(e.aggro){direction=e.direction;speed=canHit(e)?0:c.chaseSpeed;if(now<(e.agilityUntil||0))speed*=1.8;if(e.aiState==='recovering'&&e.isBoss&&canHit(e)&&!e.rapidRemaining){direction=-direction;speed=c.chaseSpeed*.35;}}
 else{if(e.position.x>e.baseX+e.patrolRange)direction=-1;if(e.position.x<e.baseX-e.patrolRange)direction=1;e.direction=direction;e.facing=direction<0?'left':'right';e.aiState='patrolling';}
 if(now<(e.slowUntil||0))speed*=.35;e.position.x=bounded(e,e.position.x+speed*direction);e.bobTime++;e.offset.y=Math.sin(e.bobTime*.08)*3;
}
function tryDodge(e,kind){const now=performance.now(),c=config(e);if(now<(e.dodgeUntil||0))return true;if(!e.aggro||e.windupUntil||e.skillWindupUntil||c.dodgeChance<=0||now<(e.dodgeReadyAt||0))return false;const threat=kind==='ultimate'?'ultimate_'+window.ShadowCombat.ultimateSerial:player.hitboxActiveUntil;if(e.lastThreat===threat)return false;e.lastThreat=threat;if(Math.random()>=c.dodgeChance)return false;const p=targetBounds(e),dir=center(e)>=p.x+p.width/2?1:-1,newX=bounded(e,e.position.x+dir*c.dodgeDistance);if(Math.abs(newX-e.position.x)<40)return false;activeEffects.push(new ArcEffect({x:center(e),y:canvas.height-floorHeight,color:c.color,radius:70,duration:24}));e.position.x=newX;e.dodgeUntil=now+220;e.dodgeReadyAt=now+c.dodgeCooldown;e.aiState='dodging';return true;}
function groundRing(x,y,rx,ry,color,progress,portal=false){
 ctx.save();ctx.fillStyle=color;ctx.strokeStyle=color;ctx.shadowColor=color;ctx.shadowBlur=8;ctx.globalAlpha=.12+.12*progress;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.55+.4*progress;ctx.lineWidth=2;ctx.setLineDash([5,4]);ctx.lineDashOffset=-performance.now()/70;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);
 ctx.globalAlpha=.45;ctx.beginPath();ctx.ellipse(x,y,rx*(.65+.25*progress),ry*.65,0,0,Math.PI*2);ctx.stroke();
 for(let i=0;i<(portal?12:7);i++){const t=performance.now()/250+i*1.7,px=x+Math.cos(t)*rx*.75,py=y-((performance.now()/30+i*9)%(portal?75:22));ctx.globalAlpha=.25+.45*progress;ctx.fillRect(Math.round(px),Math.round(py),2,2);}ctx.restore();
}
function draw(e){const now=performance.now(),c=config(e),ground=canvas.height-floorHeight;ctx.save();
 if(e.windupUntil){const b=e.warningBox||attackBox(e),p=Math.max(0,Math.min(1,1-(e.windupUntil-now)/c.windup));groundRing(b.x+b.width/2,ground-3,b.width/2,7+(e.isBoss?3:0),c.color,p);}
 if(e.skillWindupUntil){const x=e.skillKind==='teleport'?e.teleportX+e.width/2:center(e);groundRing(x,ground-3,e.skillKind==='teleport'?50:65,12,c.color,1-(e.skillWindupUntil-now)/900,true);}
 if(now<(e.dodgeUntil||0)||now<(e.agilityUntil||0)||now<(e.teleportFlashUntil||0)){ctx.fillStyle=c.color;ctx.shadowColor=c.color;ctx.shadowBlur=9;for(let j=0;j<7;j++){const t=now/130+j*.9;ctx.globalAlpha=.35;ctx.fillRect(Math.round(center(e)+Math.sin(t)*e.width*.55),Math.round(e.position.y+e.height*.5+Math.cos(t)*e.height*.45),3,3);}}
 const label=e.skillWindupUntil?({agility:'AGILIDADE',rapid:'ATAQUE RÁPIDO',teleport:'TELEPORTE'}[e.skillKind]):now<(e.dodgeUntil||0)?'ESQUIVA':'';if(label){ctx.globalAlpha=1;ctx.fillStyle='#fff0fa';ctx.font='bold 11px Arial';ctx.textAlign='center';ctx.fillText(label,center(e),e.position.y-43);}ctx.restore();}
const fieldDefs=[['detection','Distância de detecção',100,1800],['leash','Distância de retorno ao território',200,4000],['attackRange','Alcance do ataque',35,300],['attackHeight','Altura do ataque',40,220],['chaseSpeed','Velocidade de perseguição',.2,8],['windup','Preparação do golpe (ms)',250,3000],['attackCooldown','Intervalo entre ataques (ms)',400,10000],['dodgeChance','Chance de esquiva (%)',0,60],['dodgeCooldown','Intervalo entre esquivas (ms)',1500,15000],['dodgeDistance','Distância da esquiva',60,250],['abilityCooldown','Intervalo da habilidade (ms)',4000,60000],['abilityThreshold','Usar habilidade abaixo de vida (%)',10,100],['abilityDuration','Duração do bônus (ms)',1000,8000],['abilityPower','Multiplicador de dano da habilidade',1,2.5],['burstCount','Golpes na sequência rápida',2,5]];
function renderAdminAI(value){const el=document.getElementById('v14-npc-ai-form');if(!el)return;const boss=document.getElementById('admin-npc-isboss').checked,c={...defaults({isBoss:boss}),...value};el.innerHTML=`<details open><summary>IA, ataques e ultimate</summary><p>O inimigo persegue o jogador após detectar e só causa dano no alcance do golpe. Esquiva respeita chance e intervalo.</p><div class="v10-form-grid">${fieldDefs.map(([k,n,a,b])=>`<label>${n}<input id="ai-${k}" class="admin-input" type="number" min="${a}" max="${b}" step="any" value="${k==='dodgeChance'?Math.round(c[k]*100):c[k]}"></label>`).join('')}<label>Ultimate / habilidade<select id="ai-ability" class="admin-input">${[['none','Nenhuma'],['agility','Agilidade'],['teleport','Teleporte'],['rapid','Ataque rápido'],['mixed','Alternar as três habilidades']].map(([v,n])=>`<option value="${v}" ${c.ability===v?'selected':''}>${n}</option>`).join('')}</select></label><label>Cor da habilidade<input type="color" id="ai-color" value="${c.color}"></label></div></details>`;}
function readAdminAI(){const c={};for(const [k]of fieldDefs)c[k]=Number(document.getElementById('ai-'+k).value)/(k==='dodgeChance'?100:1);c.ability=document.getElementById('ai-ability').value;c.color=document.getElementById('ai-color').value;return c;}
window.ShadowCombat={tick,move,draw,tryDodge,canHit,attackBox,config,readAdminAI,renderAdminAI,ultimateSerial:0};document.addEventListener('DOMContentLoaded',()=>{renderAdminAI();document.getElementById('admin-npc-isboss')?.addEventListener('change',()=>renderAdminAI());});
})();
