// Eventos do servidor. Eventos simultâneos usam o maior bônus, sem multiplicação entre eventos.
(()=>{
let events=[],offset=0,editing='',busy=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>Date.now()+offset;
const active=()=>events.filter(e=>e.enabled&&e.startsAt<=now()&&now()<e.endsAt);
function multiplier(key,source){const phase=typeof currentPhase!=='undefined'?currentPhase?.id:'';return Math.max(1,...active().filter(e=>(!e.phaseId||e.phaseId===phase)&&(e.target==='all'||(source&&source.rewardType!=='phase'&&(e.target==='boss'?source.isBoss:!source.isBoss)))).map(e=>Number(e[key])||1));}
function accept(r){if(!r?.sucesso)throw Error(r?.mensagem||'Eventos indisponíveis. Atualize o Code.gs.');events=r.dados||[];if(Number.isFinite(r.serverTime))offset=r.serverTime-Date.now();banner();}
async function refresh(){try{accept(await apiCall('listarEventos',{}));return true}catch(err){return false}}
function summary(e){return [['xp','XP'],['coins','moedas'],['dropChance','chance de drop'],['dropQuantity','quantidade de drops']].filter(([k])=>e[k]>1).map(([k,n])=>e[k]+'x '+n).join(' · ')||'Sem bônus';}
function state(e){return !e.enabled?'Pausado':now()<e.startsAt?'Agendado':now()>=e.endsAt?'Encerrado':'Ativo';}
function remaining(ms){const min=Math.max(0,Math.ceil(ms/60000));return min>=60?Math.floor(min/60)+'h '+min%60+'min':min+'min';}
function banner(){const el=document.getElementById('v13-event-banner');if(!el)return;const rows=active();const visible=!document.getElementById("title-screen")?.classList.contains("hidden")||(typeof gameState!=="undefined"&&gameState==="playing");const title=document.getElementById('title-screen'),home=title&&!title.classList.contains('hidden');el.classList.toggle('v15-home-events',!!home);if(home&&el.parentElement!==title)title.querySelector('.v2-nav')?.after(el);else if(!home&&el.parentElement!==document.getElementById('game-wrapper'))document.getElementById('game-wrapper')?.prepend(el);el.hidden=!rows.length||!visible;el.innerHTML=rows.map(e=>`<div><img class="sb-ui-icon" src="./assets/icons/event_medal.svg" alt=""><b>${esc(e.name)}</b> · ${esc(summary(e))}<small>${esc(e.target==='all'?'Todos':e.target==='boss'?'Bosses':'NPCs')}${e.phaseId?' · '+esc(e.phaseId):''} · termina em ${remaining(e.endsAt-now())}</small></div>`).join('');}
const localDate=ms=>{const d=new Date(ms);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
function current(){return events.find(e=>e.id===editing)||{id:'',name:'',description:'',enabled:true,target:'all',phaseId:'',startsAt:Date.now(),endsAt:Date.now()+3600000,xp:2,coins:1,dropChance:1,dropQuantity:1};}
function renderAdmin(){const form=document.getElementById('v13-event-form');if(!form)return;const e=current();const input=(id,title,v,type='text',extra='')=>`<label>${title}<input class="admin-input" id="ev-${id}" type="${type}" value="${esc(v)}" ${extra}></label>`;
form.innerHTML=`<p>Agende ou inicie eventos para todos os jogadores. Horários no seu fuso local. Eventos simultâneos usam o maior bônus aplicável.</p><div class="v10-form-grid">${input('id','ID único',e.id,'text',editing?'readonly':'')}${input('name','Nome do evento',e.name)}${input('description','Descrição',e.description)}${input('startsAt','Início',localDate(e.startsAt),'datetime-local')}${input('endsAt','Fim',localDate(e.endsAt),'datetime-local')}<label>Aplicar a<select id="ev-target" class="admin-input">${[['all','Todos'],['npc','Somente NPCs'],['boss','Somente bosses']].map(([k,n])=>`<option value="${k}" ${e.target===k?'selected':''}>${n}</option>`).join('')}</select></label><label>Mapa<select id="ev-phaseId" class="admin-input"><option value="">Todos os mapas</option>${(typeof getAllPhases==='function'?getAllPhases():[]).map(p=>`<option value="${esc(p.id)}" ${p.id===e.phaseId?'selected':''}>${esc(p.name||p.nome||p.id)}</option>`).join('')}</select></label>${[['xp','Multiplicador de XP'],['coins','Multiplicador de moedas'],['dropChance','Multiplicador de chance de drop'],['dropQuantity','Multiplicador de quantidade de drops']].map(([k,n])=>input(k,n,e[k],'number','min="1" max="10" step="0.1"')).join('')}</div><div class="v13-event-actions"><label>Duração rápida<select id="ev-duration" class="admin-input"><option value="1">1 hora</option><option value="2">2 horas</option><option value="6">6 horas</option><option value="24">24 horas</option><option value="168">7 dias</option></select></label><button class="btn" id="ev-now">Definir início agora</button><button class="btn" id="ev-duration-apply">Aplicar duração</button></div><label><input type="checkbox" id="ev-enabled" ${e.enabled?'checked':''}> Evento habilitado</label><div class="v13-event-actions"><button class="btn btn-primary" id="ev-save">Salvar evento</button><button class="btn" id="ev-new">Novo evento</button><button class="btn" id="ev-refresh">Atualizar lista</button></div>`;
document.getElementById('ev-now').onclick=()=>{document.getElementById('ev-startsAt').value=localDate(now());duration()};document.getElementById('ev-duration-apply').onclick=duration;document.getElementById('ev-save').onclick=save;document.getElementById('ev-new').onclick=()=>{editing='';renderAdmin()};document.getElementById('ev-refresh').onclick=async()=>{const ok=await refresh();status(ok?'Lista atualizada.':'Não foi possível carregar. Atualize o Code.gs e a implantação.');renderAdmin()};
const list=document.getElementById('v13-event-list');list.innerHTML=events.length?events.map(x=>`<article class="v12-admin-row"><div><b>${esc(x.name)}</b><p>${esc(x.description)}</p><small>${state(x)} · ${esc(summary(x))}<br>${new Date(x.startsAt).toLocaleString('pt-BR')} até ${new Date(x.endsAt).toLocaleString('pt-BR')}<br>${esc(x.target)} · ${esc(x.phaseId||'Todos os mapas')}</small></div><div class="v13-event-actions"><button class="btn" data-edit-event="${esc(x.id)}">Editar</button><button class="btn" data-toggle-event="${esc(x.id)}">${x.enabled?'Pausar':'Habilitar'}</button><button class="btn" data-end-event="${esc(x.id)}">Encerrar</button><button class="btn" data-remove-event="${esc(x.id)}">Excluir</button></div></article>`).join(''):'<p>Nenhum evento cadastrado.</p>';
list.querySelectorAll('[data-edit-event]').forEach(b=>b.onclick=()=>{editing=b.dataset.editEvent;renderAdmin();form.scrollIntoView({behavior:'smooth'})});list.querySelectorAll('[data-toggle-event]').forEach(b=>b.onclick=()=>{const x=events.find(e=>e.id===b.dataset.toggleEvent);mutate('salvarEvento',{event:{...x,enabled:!x.enabled}})});list.querySelectorAll('[data-end-event]').forEach(b=>b.onclick=()=>{const x=events.find(e=>e.id===b.dataset.endEvent);mutate('salvarEvento',{event:{...x,enabled:false,endsAt:Math.max(x.startsAt+1,now())}})});list.querySelectorAll('[data-remove-event]').forEach(b=>b.onclick=()=>{if(confirm('Excluir este evento?'))mutate('removerEvento',{id:b.dataset.removeEvent})});}
function duration(){const start=new Date(document.getElementById('ev-startsAt').value).getTime();if(Number.isFinite(start))document.getElementById('ev-endsAt').value=localDate(start+Number(document.getElementById('ev-duration').value)*3600000)}
function status(t){const el=document.getElementById('v13-event-status');if(el)el.textContent=t}
async function mutate(action,data){if(busy)return;busy=true;status('Salvando...');try{accept(await apiCall(action,{adminID:currentUser?.id,...data}));status('Evento atualizado para todos os jogadores.');renderAdmin()}catch(err){status(err.message)}finally{busy=false}}
function save(){const e={};for(const k of ['id','name','description','target','phaseId'])e[k]=document.getElementById('ev-'+k).value.trim();for(const k of ['xp','coins','dropChance','dropQuantity'])e[k]=Number(document.getElementById('ev-'+k).value);for(const k of ['startsAt','endsAt'])e[k]=new Date(document.getElementById('ev-'+k).value).getTime();e.enabled=document.getElementById('ev-enabled').checked;if(!e.id||!e.name||!Number.isFinite(e.startsAt)||!Number.isFinite(e.endsAt)||e.endsAt<=e.startsAt){status('Preencha ID, nome e um horário de fim após o início.');return}editing=e.id;mutate('salvarEvento',{event:e})}
window.ShadowEvents={multiplier,refresh,renderAdmin,active};document.addEventListener('DOMContentLoaded',()=>{document.getElementById('admin-tab-events')?.addEventListener('click',async()=>{showAdminTab('events');await refresh();renderAdmin()});refresh();setInterval(refresh,30000);setInterval(banner,1000)});
})();
