// Destaque compartilhado da página inicial, gerenciado pelo Admin.
(()=>{
const defaults={enabled:true,mode:'boss',bossId:'necro_6',bossIds:[],imageUrl:'',title:'',description:'',label:'BOSS EM DESTAQUE',interval:12,auraColor:'#7660d9',scale:1};let config={...defaults},busy=false,previewConfig=null;
const esc=x=>window.ShadowEquipment?.escape(x)||String(x??'');
function bosses(){return [...new Map((typeof getAllNpcTypes==='function'?getAllNpcTypes():[]).filter(b=>b.isBoss).map(b=>[b.id,b])).values()];}
function select(c,time=Date.now()){const list=bosses();if(c.mode==='image')return {src:c.imageUrl,title:c.title||'Destaque ShadowBorn',description:c.description};let boss;if(c.mode==='boss')boss=list.find(b=>b.id===c.bossId);else if(c.mode==='rotation'){const rows=c.bossIds?.length?list.filter(b=>c.bossIds.includes(b.id)):list;boss=rows[Math.floor(time/(Math.max(5,c.interval)*1000))%Math.max(1,rows.length)];}else boss=list.filter(b=>!b.builtin).at(-1)||list.at(-1);boss=boss||list.at(-1);return {src:boss?getNpcSpriteSrc(boss):'./assets/necropole/06-zareth-boss-final.png',title:c.title||boss?.name||'Senhor das Sombras',description:c.description||(boss?`${boss.health} HP · ${boss.damage} dano`:'')};}
function render(){const host=document.getElementById('v15-feature');if(!host)return;host.classList.toggle('hidden',!config.enabled);host.closest('.v2-hero')?.classList.toggle('v15-no-feature',!config.enabled);if(!config.enabled)return;const item=select(config),img=document.getElementById('v15-feature-image');if(img.getAttribute('src')!==item.src)img.src=item.src;img.alt=item.title;img.style.transform=`scale(${config.scale})`;document.getElementById('v15-feature-title').textContent=item.title;document.getElementById('v15-feature-description').textContent=item.description;document.getElementById('v15-feature-label').textContent=config.label;document.getElementById('v15-feature-aura').style.background=`radial-gradient(circle,${config.auraColor}66,transparent 68%)`;}
async function refresh(){try{const r=await apiCall('listarDestaque',{});if(!r?.sucesso)return false;config={...defaults,...r.dados};if(!config.coverV17){config={...config,mode:'boss',bossId:'necro_6',title:'',description:''};}render();return true}catch{return false}}
function status(t){const el=document.getElementById('v15-home-status');if(el)el.textContent=t;}
function formValue(){const value=id=>document.getElementById('home-'+id)?.value||'';return {coverV17:true,enabled:document.getElementById('home-enabled').checked,mode:value('mode'),bossId:value('bossId'),bossIds:[...document.querySelectorAll('[data-feature-boss]:checked')].map(el=>el.value),imageUrl:value('imageUrl').trim(),title:value('title').trim(),description:value('description').trim(),label:value('label').trim(),interval:Number(value('interval')),scale:Number(value('scale')),auraColor:value('auraColor')};}
function preview(){const c=formValue(),item=select(c),img=document.getElementById('home-preview-image');previewConfig=c;img.src=item.src;img.alt=item.title;img.style.transform=`scale(${c.scale})`;document.getElementById('home-preview-title').textContent=item.title;document.getElementById('home-preview-description').textContent=item.description;document.getElementById('home-preview').style.borderColor=c.auraColor;document.getElementById('home-preview').style.opacity=c.enabled?'1':'.4';}
function renderAdmin(){const el=document.getElementById('v15-home-form');if(!el)return;const c=config,list=bosses();const input=(id,title,val,type='text',extra='')=>`<label>${title}<input class="admin-input" type="${type}" id="home-${id}" value="${esc(val)}" ${extra}></label>`;el.innerHTML=`<p>Substitua o ícone por um boss ou uma imagem própria. As configurações valem para todos os jogadores.</p><label><input type="checkbox" id="home-enabled" ${c.enabled?'checked':''}> Mostrar destaque</label><div class="v10-form-grid"><label>Modo<select id="home-mode" class="admin-input">${[['auto','Boss mais recente (automático)'],['boss','Escolher um boss'],['image','Imagem personalizada'],['rotation','Alternar bosses']].map(([k,n])=>`<option value="${k}" ${k===c.mode?'selected':''}>${n}</option>`).join('')}</select></label><label>Boss específico<select id="home-bossId" class="admin-input">${list.map(b=>`<option value="${esc(b.id)}" ${c.bossId===b.id?'selected':''}>${esc(b.name)}</option>`).join('')}</select></label>${input('imageUrl','URL da imagem',c.imageUrl)}${input('title','Título (vazio = nome do boss)',c.title)}${input('description','Descrição (vazio = atributos do boss)',c.description)}${input('label','Texto acima do título',c.label)}${input('interval','Troca automática a cada (segundos)',c.interval,'number','min="5" max="120"')}${input('auraColor','Cor da aura',c.auraColor,'color')}${input('scale','Tamanho da imagem (0.6–1.4)',c.scale,'number','min="0.6" max="1.4" step="0.1"')}</div><label>Ou envie uma imagem (será salva como PNG)<input type="file" id="home-image-file" accept="image/png,image/jpeg,image/webp,image/gif"></label><details><summary>Bosses da rotação (até 20)</summary><p>Sem seleção, alterna todos. O boss automático usa o último criado no Admin; sem cadastros próprios, usa o último da campanha.</p><div class="v15-boss-choices">${list.map(b=>`<label><input type="checkbox" data-feature-boss value="${esc(b.id)}" ${c.bossIds.includes(b.id)?'checked':''}> ${esc(b.name)}</label>`).join('')}</div></details><div id="home-preview"><img id="home-preview-image" alt="Prévia"><div><strong id="home-preview-title"></strong><p id="home-preview-description"></p></div></div><div class="v13-event-actions"><button class="btn btn-primary" id="home-save">Salvar destaque</button><button class="btn" id="home-reset">Restaurar automático</button><button class="btn" id="home-refresh">Atualizar</button></div>`;
el.querySelectorAll('input:not([type=file]),select').forEach(i=>i.addEventListener('input',preview));document.getElementById('home-image-file').onchange=upload;document.getElementById('home-save').onclick=save;document.getElementById('home-reset').onclick=()=>{config={...defaults};renderAdmin();status('Prévia restaurada. Clique Salvar destaque para aplicar.');};document.getElementById('home-refresh').onclick=async()=>{await refreshAdminContentFromServer();const ok=await refresh();renderAdmin();status(ok?'Destaque atualizado.':'Não foi possível carregar. Atualize o Code.gs.');};preview();}
async function upload(e){const file=e.target.files?.[0];if(!file)return;if(file.size>10*1024*1024){status('Use uma imagem de até 10 MB.');return;}try{const url=URL.createObjectURL(file),img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas'),scale=Math.min(1,640/Math.max(img.naturalWidth,img.naturalHeight));canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);const data=canvas.toDataURL('image/png');if(data.length>1600000){status('A imagem ficou muito grande. Use uma menor ou URL.');return;}document.getElementById('home-imageUrl').value=data;document.getElementById('home-mode').value='image';preview();status('Imagem pronta. Clique Salvar destaque.');}catch{status('Não foi possível abrir a imagem.');}}
async function save(){if(busy)return;busy=true;status('Salvando...');try{const r=await apiCall('salvarDestaque',{adminID:currentUser?.id,config:formValue()});if(!r?.sucesso)throw Error(r?.mensagem||'Falha ao salvar.');config={...defaults,...r.dados};if(!config.coverV17){config={...config,mode:'boss',bossId:'necro_6',title:'',description:''};}render();status('Destaque salvo para todos os jogadores.');}catch(e){status(e.message)}finally{busy=false;}}
window.ShadowHome={refresh,render,renderAdmin,getConfig:()=>config,select};document.addEventListener('DOMContentLoaded',()=>{document.getElementById('admin-tab-home')?.addEventListener('click',async()=>{showAdminTab('home');await refresh();renderAdmin();});document.getElementById('v15-feature-image').onerror=e=>{const img=e.target;if(!img.src.endsWith('/assets/necropole/06-zareth-boss-final.png'))img.src='./assets/necropole/06-zareth-boss-final.png';};render();refresh();setInterval(render,1000);setInterval(async()=>{if(!document.getElementById('title-screen')?.classList.contains('hidden')){await refreshBossesFromServer();await refresh();}},30000);});
})();
