// ShadowBorn v10 — catálogo visual de itens/moedas
(()=>{
const A='./assets/icons/';
const DEFAULT=[
['money','Money','currency','common','money.svg','Moeda principal do jogo.'],['diamond','Diamante VIP','currency','legendary','diamond.svg','Moeda VIP.'],['shadow_fragment','Fragmento Sombrio','currency','epic','shadow_fragment.svg','Eventos, trocas e sistemas especiais.'],['shadow_coin','Moeda Sombria','currency','legendary','shadow_coin.svg','Moeda rara das sombras.'],['honor','Ponto de Honra','currency','rare','honor.svg','Ranking e recompensas.'],['boss_token','Ficha de Boss','currency','epic','boss_token.svg','Obtida derrotando chefões.'],['guild_point','Ponto de Guilda','currency','rare','guild_point.svg','Evolução de guilda.'],['event_medal','Medalha de Evento','currency','rare','event_medal.svg','Eventos especiais.'],
['pocao_vida','Poção de Vida','consumable','common','potion_red.svg','Recupera HP.'],['pocao_mana','Poção de Mana','consumable','common','potion_blue.svg','Recupera MP.'],['pocao_vigor','Poção de Vigor','consumable','rare','potion_gold.svg','Aumenta vigor temporariamente.'],['pocao_exp','Poção de EXP','consumable','epic','potion_purple.svg','Bônus de experiência.'],['pergaminho','Pergaminho','consumable','rare','scroll.svg','Pergaminho mágico.'],['comida','Comida','consumable','common','food.svg','Regeneração.'],['elixir','Elixir','consumable','epic','elixir.svg','Elixir poderoso.'],['antidoto','Antídoto','consumable','common','antidote.svg','Remove efeitos negativos.'],
['espada_sombria','Espada Sombria','equipment','epic','sword.svg','Arma das sombras.'],['armadura_abissal','Armadura Abissal','equipment','legendary','armor.svg','Armadura de alta defesa.'],['capacete_sombrio','Capacete Sombrio','equipment','rare','helmet.svg','Proteção para a cabeça.'],['botas_sombrias','Botas Sombrias','equipment','rare','boots.svg','Botas encantadas.'],['luvas_sombrias','Luvas Sombrias','equipment','rare','gloves.svg','Luvas de combate.'],['anel_sombrio','Anel Sombrio','equipment','epic','ring.svg','Anel imbuído de poder.'],['colar_sombrio','Colar Sombrio','equipment','epic','necklace.svg','Amuleto sombrio.'],
['cristal_sombrio','Cristal Sombrio','material','rare','crystal.svg','Material raro.'],['minerio','Minério','material','common','ore.svg','Material de craft.'],['madeira','Madeira','material','common','wood.svg','Material de craft.'],['pele','Pele','material','common','leather.svg','Material de craft.'],['ferro','Ferro','material','common','iron.svg','Material de craft.'],['polvora','Pólvora','material','rare','powder.svg','Material especial.'],['essencia_sombria','Essência Sombria','material','epic','essence.svg','Evolução de equipamentos.'],['fragmento_alma','Fragmento de Alma','material','epic','soul.svg','Material especial.'],
['bau','Baú','special','rare','chest.svg','Contém recompensas.'],['chave','Chave','special','rare','key.svg','Abre baús e passagens.'],['ovo','Ovo Misterioso','special','epic','egg.svg','Pode conter uma criatura rara.'],['mapa_item','Mapa','quest','common','map.svg','Item de exploração.'],['livro','Livro Arcano','quest','rare','book.svg','Conhecimento antigo.'],['asa','Asa das Sombras','special','legendary','wing.svg','Item especial raro.'],['reliquia','Relíquia','quest','epic','relic.svg','Relíquia de missão.'],['ticket_evento','Ticket de Evento','event','rare','ticket.svg','Entrada para eventos.']
].map(x=>({id:x[0],name:x[1],type:x[2],rarity:x[3],icon:A+x[4],description:x[5]}));
let custom=[];
function all(){return DEFAULT.concat(custom)}
function get(id){return all().find(x=>x.id===id)||{id,name:String(id||'Item').replace(/_/g,' '),type:'special',rarity:'common',icon:A+'relic.svg',description:'Item do ShadowBorn.'}}
async function refresh(){try{if(typeof apiCall!=='function')return;const r=await apiCall('listarItens',{});if(r?.sucesso&&Array.isArray(r.dados))custom=r.dados.map(row=>Object.assign({id:row.id,name:row.nome},row.config||{}));}catch(e){console.warn('Itens personalizados indisponíveis',e)}}
function icon(id){return get(id).icon}
window.ShadowItems={all,get,icon,refresh,setCustom:x=>custom=x||[]};
})();
