// Patentes e pintura dos cortes: a cor final é aplicada à máscara, não por hue-rotate.
(()=>{
const esc=v=>window.ShadowEquipment?.escape(v)||String(v??'');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||a));
function palette(style,time){const base=style.colors?.length===3?style.colors:[style.color||'#bfc7ff','#ffffff',style.color||'#bfc7ff'];if(style.colorMode==='rgb'){const h=(time*.07*(Number(style.rgbSpeed)||1))%360;return [0,120,240].map(x=>`hsl(${(h+x)%360},100%,65%)`)}return style.colorMode==='three'?base:[base[0],base[0],base[0]];}
function paintCut(out,img,frame,frames,x,y,w,h,style,time=performance.now()){
 const colors=palette(style,time),temp=document.createElement('canvas');temp.width=style.pixelPattern?32:Math.max(1,Math.round((img?.naturalWidth||123)/frames));temp.height=style.pixelPattern?16:img?.naturalHeight||30;const c=temp.getContext('2d');c.imageSmoothingEnabled=false;
 if(style.pixelPattern){style.pixelPattern.forEach((p,i)=>{if(p){c.fillStyle=colors[p-1];c.fillRect(i%32,Math.floor(i/32),1,1)}})}else{if(!img?.complete||!img.naturalWidth)return;c.drawImage(img,frame*img.naturalWidth/frames,0,img.naturalWidth/frames,img.naturalHeight,0,0,temp.width,temp.height);c.globalCompositeOperation='source-in';const g=c.createLinearGradient(0,temp.height,temp.width,0);colors.forEach((v,i)=>g.addColorStop(i/2,v));c.fillStyle=g;c.fillRect(0,0,temp.width,temp.height);}
 out.save();out.imageSmoothingEnabled=false;if(style.aura!==false){out.shadowColor=colors[2];out.shadowBlur=12;}out.drawImage(temp,x,y,w,h);out.restore();
}
SlashEffect.prototype.draw=function(){const left=this.facing==='left',w=this.attackRange||150,h=80;ctx.save();ctx.translate(this.position.x+(left?w:0)+(left?-1:1)*Math.min(1,Math.max(0,(performance.now()-(this.launchedAt||performance.now()))/200))*40,this.position.y);ctx.scale(left?-1:1,1);paintCut(ctx,this.image,this.currentSpriteFrame,this.totalSpriteFrames,0,0,w,h,this.cutStyle||{});ctx.restore();};
function rankMarkup(level){const r=getPatenteByLevel(level);return `<img class="v14-rank-icon" src="${esc(r.image)}" title="${esc(r.name)}" alt="${esc(r.name)}">`;}
let lastRank='';function ranks(){const data=window.ShadowRPG?.getData();if(!data)return;const r=getPatenteByLevel(data.level),key=JSON.stringify([data.level,data.xp]);if(key===lastRank)return;lastRank=key;const img=document.getElementById('v14-home-rank-icon');if(img){img.src=r.image;img.alt=r.name;}const name=document.getElementById('v14-home-rank-name');if(name)name.textContent=r.name;const profile=document.getElementById('v14-profile-rank');if(profile)profile.innerHTML=rankMarkup(data.level)+`<small>${esc(r.name)}</small>`;const next=document.getElementById('v14-next-rank');if(next)next.innerHTML=data.level<100?`<small>Próxima patente: ${esc(getPatenteByLevel(data.level+1).name)}</small><span>${data.xp} / ${100+(data.level-1)*75} XP</span>`:'<small>Divindade do Vazio X · patente máxima</small>';}
function defaultPattern(){return Array.from({length:512},(_,i)=>{const x=i%32,y=Math.floor(i/32),v=(x-10)**2/370+(y-14)**2/190;return v>.48&&v<.85&&y<14?(x<14?1:x<23?2:3):0;});}
let pattern=null,pixelBrush=1,previewHandle=0;
function enhanceCatalogForm(i){cancelAnimationFrame(previewHandle);const form=document.getElementById('v12-catalog-form');if(!form)return;let host=document.getElementById('v14-cut-editor');host?.remove();if(i.category!=='attack')return;pattern=i.pixelPattern?[...i.pixelPattern]:null;pixelBrush=1;host=document.createElement('section');host.id='v14-cut-editor';host.innerHTML=`<h4>Editor de corte · cores e aura</h4><div class="v10-form-grid"><label>Modo de cor<select id="cut-mode" class="admin-input"><option value="solid">Cor sólida</option><option value="three">Três cores</option><option value="rgb">RGB animado (arco-íris)</option></select></label><label>Segunda cor<input id="cut-color2" type="color" value="${esc(i.colors?.[1]||'#ffffff')}"></label><label>Terceira cor / aura<input id="cut-color3" type="color" value="${esc(i.colors?.[2]||i.color||'#bfc7ff')}"></label><label>Velocidade RGB<input id="cut-rgb-speed" class="admin-input" type="number" min="0.2" max="3" step="0.1" value="${i.rgbSpeed||1}"></label><label>Alcance do corte (90–240)<input id="cut-range" class="admin-input" type="number" min="90" max="240" value="${i.attackRange||150}"></label><label>Velocidade visual (0.5–2)<input id="cut-speed" class="admin-input" type="number" min="0.5" max="2" step="0.1" value="${i.effectSpeed||1}"></label></div><label><input id="cut-aura" type="checkbox" ${i.aura!==false?'checked':''}> Aura no corte</label><canvas id="cut-preview" width="384" height="144" aria-label="Prévia animada do corte"></canvas><details><summary>Desenhar o próprio corte em pixel art (32 × 16)</summary><p>Escolha uma cor e arraste no quadro. O pixel art substitui a imagem do corte. O botão direito apaga.</p><div class="v13-event-actions"><button type="button" class="btn" data-brush="1">Cor 1</button><button type="button" class="btn" data-brush="2">Cor 2</button><button type="button" class="btn" data-brush="3">Cor 3</button><button type="button" class="btn" data-brush="0">Borracha</button><button type="button" class="btn" id="cut-pixel-clear">Limpar pixels</button><button type="button" class="btn" id="cut-pixel-reset">Usar spritesheet original</button></div><canvas id="cut-pixels" width="384" height="192" aria-label="Editor pixel art do corte"></canvas></details><p>As mudanças aparecem na prévia imediatamente. Clique Salvar cadastro para publicar.</p>`;
form.querySelector('#v12-save-catalog').before(host);document.getElementById('cut-mode').value=i.colorMode||'solid';if(i.colors?.[0])document.getElementById('v12-color').value=i.colors[0];host.querySelectorAll('[data-brush]').forEach(b=>b.onclick=()=>pixelBrush=Number(b.dataset.brush));document.getElementById('cut-pixel-clear').onclick=()=>pattern=Array(512).fill(0);document.getElementById('cut-pixel-reset').onclick=()=>pattern=null;
const pixel=document.getElementById('cut-pixels');pixel.oncontextmenu=e=>e.preventDefault();let dragging=false;function paint(e){const b=pixel.getBoundingClientRect(),x=Math.floor((e.clientX-b.left)/b.width*32),y=Math.floor((e.clientY-b.top)/b.height*16);if(x<0||x>31||y<0||y>15)return;if(!pattern)pattern=defaultPattern();pattern[y*32+x]=e.buttons===2?0:pixelBrush;}pixel.onpointerdown=e=>{e.preventDefault();dragging=true;pixel.setPointerCapture(e.pointerId);paint(e)};pixel.onpointermove=e=>{if(dragging)paint(e)};pixel.onpointerup=pixel.onpointercancel=()=>dragging=false;
const preview=document.getElementById('cut-preview'),pc=preview.getContext('2d'),gc=pixel.getContext('2d');function render(time){if(!host.isConnected||host.closest('.hidden'))return;const style=readCutForm(),colors=palette(style,time);pc.fillStyle='#101324';pc.fillRect(0,0,384,144);const source=document.getElementById('v12-effect-src')?.value||ASSET_PATHS.slash,frames=Number(document.getElementById('v12-effect-frames')?.value)||5,img=getImage(source);paintCut(pc,img,Math.floor(time/100*(style.effectSpeed||1))%frames,frames,65,24,240,96,style,time);gc.fillStyle='#101324';gc.fillRect(0,0,384,192);(pattern||defaultPattern()).forEach((p,n)=>{if(p){gc.fillStyle=colors[p-1];gc.fillRect(n%32*12,Math.floor(n/32)*12,12,12)}});gc.strokeStyle='#ffffff18';gc.lineWidth=1;for(let x=0;x<=384;x+=12){gc.beginPath();gc.moveTo(x,0);gc.lineTo(x,192);gc.stroke()}for(let y=0;y<=192;y+=12){gc.beginPath();gc.moveTo(0,y);gc.lineTo(384,y);gc.stroke()}previewHandle=requestAnimationFrame(render);}previewHandle=requestAnimationFrame(render);
}
function readCutForm(){if(!document.getElementById('cut-mode'))return {};return {colors:[document.getElementById('v12-color').value,document.getElementById('cut-color2').value,document.getElementById('cut-color3').value],colorMode:document.getElementById('cut-mode').value,aura:document.getElementById('cut-aura').checked,attackRange:clamp(document.getElementById('cut-range').value,90,240),effectSpeed:clamp(document.getElementById('cut-speed').value,.5,2),rgbSpeed:clamp(document.getElementById('cut-rgb-speed').value,.2,3),pixelPattern:pattern?[...pattern]:undefined};}
window.ShadowV14={paintCut,palette,rankMarkup,enhanceCatalogForm,readCutForm,ranks};document.addEventListener('DOMContentLoaded',()=>{ranks();setInterval(ranks,500);});
})();
